language: go
go:
  - 1.13.x
  - 1.14.x
go_import_path: zgo.at/isbot
env: ['GO111MODULE=on']
notifications:
  email: false
install:
script: |
  go test -race \
    -coverprofile=coverage.txt \
    -coverpkg=./... \
    ./...
