name: 'test backend'
on:   ['push', 'pull_request']

jobs:
  test:
    name:    'test (linux)'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'test (linux)'
        run: |
          go test -race ./...

  staticcheck:
    name:    'staticcheck'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'dominikh/staticcheck-action@v1.3.1'
        with: {version: '2025.1.1'}
